config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  

  resources :clubs
  resources :students
  resources :sessions
  resources :events

#  root			        	'students#new'
 # get    'home'   =>  'static_pages#home'
#  get    'login'   => 'sessions#new'
#  post   'login'   => 'sessions#create'
#  delete 'logout'  => 'sessions#destroy'
  
#  get     'error' => 'students#error'



#resources :students
#resources :sessions
  resources :account_activations, only: [:edit]
  root 'static_pages#home'
  #root  'students#new'
  get   'contact' => 'static_pages#contact'
  get   'signup'  => 'students#new'
  get    'login'	=> 'sessions#new'
  post   'login'	=> 'sessions#create'
  delete 'logout'	=> 'sessions#destroy'
  get    'error'	=> 'students#error'
  get	 'myClubs'	=> 'clubs#list'
  get	 'allClubs'	=> 'clubs#index'
  get 'browseByCategory' => 'clubs#categories'
  post 'join'     => 'clubs#join'
  delete  'event' =>  'events#destroy'
  get    'signUp' => 'events#sign_up'
  get    'drop' => 'events#drop'
  get   'student_events' => 'events#student_events'
  
  
  # call back route from Google
  get "/auth/:provider/callback" => "sessions#access"

end


# comments are from the merge

app/models/club.rb
class Club < ActiveRecord::Base
	has_and_belongs_to_many :students
	has_many :events

	has_one :token
	
  validates :name, presence: true, uniqueness: { case_sensitive: false, message: "is already taken by another club" }, length: { minimum: 3, message: "has to be at least 3 letters long"}
  validates :description, presence: true, length: { maximum: 300, message: "is too long"}
 

  validates :website, presence: false, allow_blank: true, allow_nil: true
 
  validates :insta, presence: false, allow_blank: true, allow_nil: true
   
  validates :twitt, presence: false, allow_blank: true, allow_nil: true 
 
  validates :SunDesc, presence: false, allow_blank: true, allow_nil: true
  validates :MonDesc, presence: false, allow_blank: true, allow_nil: true
  validates :TueDesc, presence: false, allow_blank: true, allow_nil: true
  validates :WedDesc, presence: false, allow_blank: true, allow_nil: true
  validates :ThuDesc, presence: false, allow_blank: true, allow_nil: true
  validates :FriDesc, presence: false, allow_blank: true, allow_nil: true
  validates :SatDesc, presence: false, allow_blank: true, allow_nil: true
  validates :SunTime, presence: false, allow_blank: true, allow_nil: true
  validates :MonTime, presence: false, allow_blank: true, allow_nil: true
  validates :TueTime, presence: false, allow_blank: true, allow_nil: true
  validates :WedTime, presence: false, allow_blank: true, allow_nil: true
  validates :ThuTime, presence: false, allow_blank: true, allow_nil: true
  validates :FriTime, presence: false, allow_blank: true, allow_nil: true
  validates :SatTime, presence: false, allow_blank: true, allow_nil: true
  validates :SunPlace, presence: false, allow_blank: true, allow_nil: true
  validates :MonPlace, presence: false, allow_blank: true, allow_nil: true
  validates :TuePlace, presence: false, allow_blank: true, allow_nil: true
  validates :WedPlace, presence: false, allow_blank: true, allow_nil: true
  validates :ThuPlace, presence: false, allow_blank: true, allow_nil: true
  validates :FriPlace, presence: false, allow_blank: true, allow_nil: true
  validates :SatPlace, presence: false, allow_blank: true, allow_nil: true

def self.search(search)
  #iLIKE is used for postgres
  
  #where("name iLIKE ?", "%#{search}%")
  
  #search in both name and club description
  where("name iLIKE ? OR description iLIKE ?", "%#{search}%", "%#{search}%")
  
end
  
  
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
	
	#The club form
	def new
		@club = Club.new
	end
	
	#Display the info for a single club
	def show
		@club = Club.find(params[:id])
	end

	#Join the club whose page you're on
	def join
		@club = Club.find(params[:id])
		@club.students << current_student
		redirect_to myClubs_url
	end

	#List all clubs in model
	def index
		@clubs = Club.all.order(:name)
		if params[:search]
    		@clubs = Club.search(params[:search]).order(:name)
		else
    		@clubs = Club.all.order(:name)
 		end
	end

	def categories
		@clubs = Club.all.order(:name)
	end
	
	#List all clubs that the current student is a member/admin of
	def list
		@clubs = current_student.clubs
	end

	#Save the club to the model and update join relation
	def create
		#First save the new club
	    @club = Club.new(club_params)
	    @club.admin_id = current_student.id
	    if !@club.save
	      redirect_to current_student
	    else
	    #Then record the relationship between the creator and the club
	    @club.students << current_student
	    redirect_to myClubs_url
	    end
  	end
	
		
	
	def edit
		@club = Club.find(params[:id])
	end
	
	
	def update
		@club = Club.find(params[:id])
		if @club.update_attributes(club_params)
			redirect_to @club
		else
			render 'edit'
		end
	end
	
	
	
	#No option to do this yet
	def destroy

	end

	private

		def club_params
   			params.require(:club).permit(:name, :description, :website, :insta, :twitt, :choice1, :choice2, :choice3, :choice4, :choice5, :choice6, :choice7, :choice8, :choice9, :choice10,:SunDesc, 	:MonDesc, 	:TueDesc, 	:WedDesc, 	:ThuDesc, 	:FriDesc, 	:SatDesc, 	:SunTime, 	:MonTime, 	:TueTime, 	:WedTime, 	:ThuTime, 	:FriTime, 	:SatTime, 	:SunPlace, 	:MonPlace, 	:TuePlace, 	:WedPlace, 	:ThuPlace, 	:FriPlace, 	:SatPlace)
  			#params.require(:club).permit(:name, :description, :website, :choice1, :choice2, :choice3, :choice4, :choice5, :choice6, :choice7, :choice8, :choice9, :choice10,:SunDesc, 	:MonDesc, 	:TueDesc, 	:WedDesc, 	:ThuDesc, 	:FriDesc, 	:SatDesc, 	:SunTime, 	:MonTime, 	:TueTime, 	:WedTime, 	:ThuTime, 	:FriTime, 	:SatTime, 	:SunPlace, 	:MonPlace, 	:TuePlace, 	:WedPlace, 	:ThuPlace, 	:FriPlace, 	:SatPlace)
  		end
end

app/helpers/clubs_helper.rb
module ClubsHelper
	
	def access_granted_for_club?(club)
		if club.token != nil
			club.token.access_token != nil
		end
	end
end

app/views/clubs/_clubForm.html.erb
<%#FOR New Club, THE FORM HAS TO START WITH <%= form_for(:club, url: clubs_path) do |f| %> 
<%#BUT FOR EDITING, THE FORM HAS TO START WITH <%= form_for @club  do |f| %> 
<%= form_for(:club, url: clubs_path) do |f| %>

  <table border ="0" style="border:none" height="300px">
    <tr>
       <td><b><%= f.label :name, "Club Name"%></b></td>
       <td> <%= f.text_field :name, placeholder: "Club Name", :size => 30 %></td>
    </tr>
    <tr>
       <td><b><%= f.label :description, "Description (try to provide enough info)"%></b></td>
       <%# <td><p><small> Try and provide enough information</small></p></td>   
    </tr>
    <tr> %>
       <td><%= f.text_area :description, placeholder: "Club Description" , size: "29x6"  %></td>
    </tr>
    <tr>
      <td><b><%= f.label :website, "Club website (optional)" %></b></td>
      <td> <%= f.text_field :website , value: "http://", :size => 30 %></td>
    </tr>
    
    <tr>
    <td><b><%= f.label :insta, "Instagram handle (optional)" %></b></td>
    <td>@<%= f.text_field :insta , placeholder: "simonfraseru", :size => 20 %></td>
    </tr>
    <tr>
    <td><b><%= f.label :twitt, "Twitter handle (optional)" %></b></td>
    <td>@<%= f.text_field :twitt , placeholder: "sfu", :size => 20 %></td>
    </tr>
    
    <tr>
      <td><b>Check categories your club belongs to:</b></td>
      <td><small>This will help students find you!</small></td>
    </tr>
    
    <%# Note: please keep space between <f.checkbox> and <f.label> %>
    <tr>
      <td><%= f.check_box :choice1, {}, true, false %> <%= f.label :choice1, "Academics" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice2, {}, true, false %> <%= f.label :choice2, "Cultural, Religious, Nationalities" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice3, {}, true, false %> <%= f.label :choice3, "Department or Faculty Student Union" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice4, {}, true, false %> <%= f.label :choice4, "Food" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice5, {}, true, false %> <%= f.label :choice5, "Fraternity or Sorority" %></td>
    </tr>    
    <tr>
      <td><%= f.check_box :choice6, {}, true, false %> <%= f.label :choice6, "Music" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice7, {}, true, false %> <%= f.label :choice7, "Professional Development, Careers" %></td>
    </tr>
     <tr>
      <td><%= f.check_box :choice8, {}, true, false %> <%= f.label :choice8, "Science and Technology" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice9, {}, true, false %> <%= f.label :choice9, "Sports and Fitness" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice10, {}, true, false %> <%= f.label :choice10, "Volunteer Work or Social Activism" %></td>
    </tr>
  </table>  
   

   <br>
   <b>Enter the normal weekly meetings for your club including meeting time and location:</b>
   <table style = "width:100%;"> 
    <tr>
     <td><b><b></td>
     <td><b>Sunday<b></td>
     <td><b>Monday<b></td>
     <td><b>Tuesday<b></td>
     <td><b>Wednesday<b></td>
     <td><b>Thursday<b></td>
     <td><b>Friday<b></td>
     <td><b>Saturday<b></td>
    </tr>
   <tr>
     <td><b>Meeting Description</b></td>
     <td><%= f.text_field :SunDesc, placeholder: "i.e. Team Practice" %></td>
     <td><%= f.text_field :MonDesc %></td>
     <td><%= f.text_field :TueDesc, placeholder: "i.e. Team Gym Session" %></td>
     <td><%= f.text_field :WedDesc %></td>
     <td><%= f.text_field :ThuDesc %></td>
     <td><%= f.text_field :FriDesc %></td>
     <td><%= f.text_field :SatDesc %></td>
   </tr>
   <tr>
     <td><b>Meeting Time</b></td>
     <td><%= f.text_field :SunTime, placeholder: "7pm to 10pm" %></td>
     <td><%= f.text_field :MonTime %></td>
     <td><%= f.text_field :TueTime, placeholder: "8:30pm to 11:30pm" %></td>
     <td><%= f.text_field :WedTime %></td>
     <td><%= f.text_field :ThuTime %></td>
     <td><%= f.text_field :FriTime %></td>
     <td><%= f.text_field :SatTime %></td>
   </tr>
      <tr>
     <td><b>Meeting Location</b></td>
     <td><%= f.text_field :SunPlace, placeholder: "SFU West Gym" %></td>
     <td><%= f.text_field :MonPlace %></td>
     <td><%= f.text_field :TuePlace, placeholder: "SFU Fitness Centre" %></td>
     <td><%= f.text_field :WedPlace %></td>
     <td><%= f.text_field :ThuPlace %></td>
     <td><%= f.text_field :FriPlace %></td>
     <td><%= f.text_field :SatPlace %></td>
   </tr>
   
   <tr>
     <%# blank row %>
   </tr> 
    <tr>
       <td><%= f.submit "Create Club" %></td>
    </tr>
   </table>
<% end %>
<br>

app/views/clubs/_listAllClubs.html.erb
<!DOCTYPE html>
<html>
<h1> All Clubs </h1>
<% if @clubs.any? %>
	<table style="width: 70%">
		<% @clubs.each do |club| %>
			<tr>
			<td><%= button_to "Visit Club Page", { controller: 'clubs', action: 'show', id: club.id }, { method: :get } %>   </td>
			<td><strong><%= club.name %>        </strong></td>
			<td><%= club.description %></td>
			</tr>
		<% end %>
	</table>
<% end %>
<br>



<style>

table {
    border-collapse: collapse;
    width: 100%;
    table-layout: fixed;
    overflow-x: auto;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
    word-wrap:break-word
}
tr:hover{background-color:#cce6ff}


</style>

</html>

app/views/clubs/_listMyClubs.html.erb
<!DOCTYPE html>
<html>
	
<% if @clubs.any? %>
	
	<table style = "width: 70%">
		
		<tr><h1>Clubs I'm in:</h1></tr>
			<% @clubs.each do |club| %>
				<tr>
				<td><%= button_to "Visit Club Page", { controller: 'clubs', action: 'show', id: club.id }, { method: :get } %>   
				</td>
				<td><strong><%= club.name %>        
				</strong></td>
				<td><%= club.description %>
				</td>
				<% if club.admin_id == current_student.id%>
					<td><i>*I admin this club</i></td>
				<%end%>
				</tr>
			<%end%>
	</table>

<% else %>
	<h2>You're not in any clubs! Take a look and browse all clubs offered: <%= button_to "List All Clubs", allClubs_path, method: "get" %></h2>
	<h2>Or use this tool to browse according to your interests: <%= button_to "Browse Clubs by Category", browseByCategory_path, :method => :get %></h2>
<% end %>

<style>

table {
    border-collapse: collapse;
    width: 100%;
    table-layout: fixed;
    overflow-x: auto;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
    word-wrap:break-word
}
tr:hover{background-color:#cce6ff}

i{
	color: green;
}

</style>

</html>

app/views/clubs/_searchClubs.html.erb
<%= form_tag(clubs_path, :method => "get", id: "club-search-form") do %>
<%= text_field_tag :search, params[:search], :size => 35 , placeholder: "Search clubs by name or description", :id => "searchField" %>
<%= submit_tag "Search Clubs" %> <button onclick="resetForm()">Clear Search</button>

<% end %>

<% if @clubs.present? %>
    <%# if present then then clubs will be shown in index %>
<% else %>
  <p>There are no clubs containing the term(s) <%= params[:search] %>.</p>
<% end %>

<script>
function resetForm() {
var form = document.getElementById("searchField");
form.value = ''
}
</script>

app/views/clubs/categories.html.erb
<!DOCTYPE html>
<html>
<% provide(:title, "Browse by Category") %>
<%= render 'browseByCategory' %>

</html>

app/views/clubs/edit.html.erb
<% provide(:title, "Edit Club Settings") %>
<h2>Edit Club Settings</h2>

<%#FOR EDITING, THE FORM HAS TO START WITH <%= form_for @club  do |f| %> 
<%#BUT for New Club, THE FORM HAS TO START WITH <%= form_for(:club, url: clubs_path) do |f| %> 
<%= form_for @club  do |f| %>

  <table border ="0" style="border:none" height="300px">
    <tr>
       <td><b><%= f.label :name, "Club Name"%></b></td>
       <td> <%= f.text_field :name, placeholder: "Club Name", :size => 30 %></td>
    </tr>
    <tr>
       <td><b><%= f.label :description, "Description (try to provide enough info)"%></b></td>
       <%# <td><p><small> Try and provide enough information</small></p></td>   
    </tr>
    <tr> %>
       <td><%= f.text_area :description, placeholder: "Club Description" , size: "29x6"  %></td>
    </tr>
    <tr>
      <td><b><%= f.label :website, "Club website (optional)" %></b></td>
      <td> <%= f.text_field :website , placeholder: "http://", :size => 30 %></td>
    </tr>
    
    <tr>
    <td><b><%= f.label :insta, "Instagram handle (optional)" %></b></td>
    <td>@<%= f.text_field :insta , placeholder: "simonfraseru", :size => 20 %></td>
    </tr>
    <tr>
    <td><b><%= f.label :twitt, "Twitter handle (optional)" %></b></td>
    <td>@<%= f.text_field :twitt , placeholder: "sfu", :size => 20 %></td>
    </tr>
    
    <tr>
      <td><b>Check categories your club belongs to:</b></td>
      <td><small>This will help students find you!</small></td>
    </tr>
    
    <%# Note: please keep space between <f.checkbox> and <f.label> %>
    <tr>
      <td><%= f.check_box :choice1, {}, true, false %> <%= f.label :choice1, "Academics" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice2, {}, true, false %> <%= f.label :choice2, "Cultural, Religious, Nationalities" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice3, {}, true, false %> <%= f.label :choice3, "Department or Faculty Student Union" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice4, {}, true, false %> <%= f.label :choice4, "Food" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice5, {}, true, false %> <%= f.label :choice5, "Fraternity or Sorority" %></td>
    </tr>    
    <tr>
      <td><%= f.check_box :choice6, {}, true, false %> <%= f.label :choice6, "Music" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice7, {}, true, false %> <%= f.label :choice7, "Professional Development, Careers" %></td>
    </tr>
     <tr>
      <td><%= f.check_box :choice8, {}, true, false %> <%= f.label :choice8, "Science and Technology" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice9, {}, true, false %> <%= f.label :choice9, "Sports and Fitness" %></td>
    </tr>
    <tr>
      <td><%= f.check_box :choice10, {}, true, false %> <%= f.label :choice10, "Volunteer Work or Social Activism" %></td>
    </tr>
  </table>  
   
   
   <br>
   <b>Enter the normal weekly meetings for your club including meeting time and location:</b>
   <table> 
   <tr>
     <td><b><b></td>
     <td><b>Sunday<b></td>
     <td><b>Monday<b></td>
     <td><b>Tuesday<b></td>
     <td><b>Wednesday<b></td>
     <td><b>Thursday<b></td>
     <td><b>Friday<b></td>
     <td><b>Saturday<b></td>
    </tr>
   <tr>
     <td><b>Meeting Description</b></td>
     <td><%= f.text_field :SunDesc %></td>
     <td><%= f.text_field :MonDesc %></td>
     <td><%= f.text_field :TueDesc %></td>
     <td><%= f.text_field :WedDesc %></td>
     <td><%= f.text_field :ThuDesc %></td>
     <td><%= f.text_field :FriDesc %></td>
     <td><%= f.text_field :SatDesc %></td>
   </tr>
   <tr>
     <td><b>Meeting Time</b></td>
     <td><%= f.text_field :SunTime %></td>
     <td><%= f.text_field :MonTime %></td>
     <td><%= f.text_field :TueTime %></td>
     <td><%= f.text_field :WedTime %></td>
     <td><%= f.text_field :ThuTime %></td>
     <td><%= f.text_field :FriTime %></td>
     <td><%= f.text_field :SatTime %></td>
   </tr>
      <tr>
     <td><b>Meeting Location</b></td>
     <td><%= f.text_field :SunPlace %></td>
     <td><%= f.text_field :MonPlace %></td>
     <td><%= f.text_field :TuePlace %></td>
     <td><%= f.text_field :WedPlace %></td>
     <td><%= f.text_field :ThuPlace %></td>
     <td><%= f.text_field :FriPlace %></td>
     <td><%= f.text_field :SatPlace %></td>
   </tr>
   
   <tr>
     <%# blank row %>
   </tr> 
    <tr>
       <td><%= f.submit "Save Changes" %></td>
    </tr>
   </table>
<% end %>
<br>

<%= button_to "Cancel Editing", @club, { method: :get } %>

app/views/clubs/index.html.erb
<!DOCTYPE html>
<html>
<% provide(:title, "Clubs") %>

<br>

<%= render 'searchClubs' %>

<br>

<%= render 'listAllClubs' %>


</html>

app/views/clubs/list.html.erb
<!DOCTYPE html>
<html>
<% provide(:title, "Your Clubs") %>
<%= render 'listMyClubs' %>

</html>

app/views/clubs/new.html.erb
<% provide(:title, "Create Club") %>
<%= render 'clubForm' %>

app/views/clubs/show.html.erb
<!DOCTYPE html>
<html>
<% require 'uri' %>
<% provide(:title, @club.name) %>



<h1><%= @club.name %></h1>
<p><%= @club.description %></p>

<% if @club.website =~ URI::regexp %>
    <% if @club.website == "http://" %>
    <% else %>
    <p>Club Website: <%= link_to(@club.website, @club.website, target: '_blank') %></p>
    <%end%>
<%end%> 

<% if @club.insta != nil %>	
  <% if @club.insta != ""%>
     <p>Club Instagram: @<%= link_to(@club.insta, "http://instagram.com/#{@club.insta}", target: '_blank') %></p>	
 <%end%>
 <%end%>
	
 <% if @club.twitt != nil %>	
     <% if @club.twitt != "" %>
     <p>Club Twitter: @<%= link_to(@club.twitt, "http://twitter.com/#{@club.twitt}", target: '_blank') %></p>	
 <%end%>	
 <%end%>



<% if @club.admin_id == current_student.id  %>
    <%= link_to "<button>Edit Club Settings</button>".html_safe, edit_club_path(@club) %>
    <% if !access_granted_for_club?(@club) %>
      <div>
        <strong><p>Click <%= link_to "here","/auth/google_oauth2?name=#{@club.name}" ,target: '_blank'%> to show the club's calendar.
        This must be a separate calendar from your own personal calendar.</strong></p>
      </div>
    <% end %>
<% end %>

<br>

 <p>This club has <%= pluralize(@club.students.count, "member") %> in it.</p>  


<% if @club.admin_id == current_student.id  %>

<div class="container">
    <div class="row">
            <h2>Club Member Names:</h2>
            <ol> <%# ordered list %>
            <% @club.students.each do |student| %>
            <li><%= student.name %></li>
            </br>
            <% end %>
            <ol> <%# end ordered list %>
    </div>
</div>

  <div>
      <% if @club.events.empty? %>
        <p>This club has no events. Click to create a new event.</p>
      <% else %>
        <p>This club has <%= @club.events.size %> events.</p>
      <% end %>
      <%= button_to 'Create Event', new_event_path, {:method => :get, :params => {:name => "#{@club.name}"}} %>
      <%= button_to 'Show Events', events_path, {:method => :get, :params => {:name => "#{@club.name}"}} %>
  </div>


<% else %>
    <% if !@club.events.empty? %>
        <p>This club has <%= @club.events.size %> events. Click below to see a list of events.</p>
        <%= button_to 'Show Events', events_path, {:method => :get, :params => {:name => "#{@club.name}"}} %>
    <% else %>
        <p>There are currently no events for this club.</p>
    <% end %>

  <% x=0 %>
  <% current_student.clubs.each do |inClub|   %>
        <% if inClub.id == @club.id %>
          <% x= x+1%>
        <% end %>
  <%end%>
  
  <% if x == 0 %>
    <%= button_to "Join Club", { controller: 'clubs', action: 'join', id: @club.id }, { method: :post } %>
  <% end %>
  
<% end %>




<h2>Weekly Meetings:</h2>
<table>
  
  <caption>This club meets regularly at these times:</caption>
  <thead>
   <tr>
     <td><b><b></td>
     <td><b>Sunday<b></td>
     <td><b>Monday<b></td>
     <td><b>Tuesday<b></td>
     <td><b>Wednesday<b></td>
     <td><b>Thursday<b></td>
     <td><b>Friday<b></td>
     <td><b>Saturday<b></td>
    </tr>
  </thead>
  <tbody>
       <tr>
     <td><b>Description</b></td>
     <td><%= @club.SunDesc %></td>
     <td><%= @club.MonDesc %></td>
     <td><%= @club.TueDesc %></td>
     <td><%= @club.WedDesc %></td>
     <td><%= @club.ThuDesc %></td>
     <td><%= @club.FriDesc %></td>
     <td><%= @club.SatDesc %></td>
   </tr>
   <tr>
     <td><b>Time</b></td>
     <td><%= @club.SunTime %></td>
     <td><%= @club.MonTime %></td>
     <td><%= @club.TueTime %></td>
     <td><%= @club.WedTime %></td>
     <td><%= @club.ThuTime %></td>
     <td><%= @club.FriTime %></td>
     <td><%= @club.SatTime %></td>
   </tr>
      <tr>
     <td><b>Location</b></td>
     <td><%= @club.SunPlace %></td>
     <td><%= @club.MonPlace %></td>
     <td><%= @club.TuePlace %></td>
     <td><%= @club.WedPlace %></td>
     <td><%= @club.ThuPlace %></td>
     <td><%= @club.FriPlace %></td>
     <td><%= @club.SatPlace %></td>
   </tr>
   
   <tr>
     <%# blank row %>
   </tr>
  </tbody>
</table>

<% if @club.admin_id == current_student.id  %> <%#only club admin view club calendar, to avoid permission/access issues %>
  <% if access_granted_for_club?(@club) %>
    <h2>Club Calendar:</h2>
    <p><%= link_to('Plan your trip with translink', 'http://tripplanning.translink.ca/', target: '_blank') %>
    <br>
    </p>
    <div>
      <iframe src="<%= embed_link(@club) %>" 
      style="border: 0" width="800" height="600" frameborder="0" scrolling="no">
      </iframe>
    </div>
  <% end %>
<%end%>  <%#end only club admin views calendar %>

<style>

table {
    border-collapse: collapse;
    width: 100%;
    table-layout: fixed;
    overflow-x: auto;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
    word-wrap:break-word
}
td:hover{background-color:#cce6ff}

</style>


</html>