config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  

  resources :clubs
  resources :students
  resources :sessions
  resources :events

#  root			        	'students#new'
 # get    'home'   =>  'static_pages#home'
#  get    'login'   => 'sessions#new'
#  post   'login'   => 'sessions#create'
#  delete 'logout'  => 'sessions#destroy'
  
#  get     'error' => 'students#error'



#resources :students
#resources :sessions
  resources :account_activations, only: [:edit]
  root 'static_pages#home'
  #root  'students#new'
  get   'contact' => 'static_pages#contact'
  get   'signup'  => 'students#new'
  get    'login'	=> 'sessions#new'
  post   'login'	=> 'sessions#create'
  delete 'logout'	=> 'sessions#destroy'
  get    'error'	=> 'students#error'
  get	 'myClubs'	=> 'clubs#list'
  get	 'allClubs'	=> 'clubs#index'
  get 'browseByCategory' => 'clubs#categories'
  post 'join'     => 'clubs#join'
  delete  'event' =>  'events#destroy'
  get    'signUp' => 'events#sign_up'
  get    'drop' => 'events#drop'
  get   'student_events' => 'events#student_events'
  
  
  # call back route from Google
  get "/auth/:provider/callback" => "sessions#access"

end


# comments are from the merge

app/models/student.rb
class Student < ActiveRecord::Base
  
  attr_accessor :activation_token
  before_save :downcase_email
  before_create :create_activation_digest
  has_secure_password
  
  has_and_belongs_to_many :clubs
  has_many :events#, :through => :clubs
  has_one :token
  
  before_save { email.downcase! }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false, message: "already in use" }, format: { with: VALID_EMAIL_REGEX }, length: { maximum: 255, message: "email was too long ( must be less than 256 chars )" }
  validates :name, presence: true, length: { maximum: 40, message: "was too long ( max 40 characters )" }
  validates :password, presence: true, length: { minimum: 4, message: "minimum length is 4 characters" }
  validate  :valid_password_complexity?
  
  # Returns the hash digest of the given string.
  def Student.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def Student.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  private
    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = Student.new_token
      self.activation_digest = Student.digest(activation_token)
    end

    #Check that password fits complexity standard (1 letter & 1 num)
    def valid_password_complexity?
      if not self.password =~ /[a-z]/i 
        errors.add(:password, "must contain at least 1 letter")
        return false
      end
      if not self.password =~ /\d/
        errors.add(:password, "must contain at least 1 number")
        return false
      end
      return true
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :logged_in_student, only: [:show]
    before_action :current_logged_in_student,   only: [:show]

  def show
    @student = Student.find(params[:id])
    redirect_to root_url and return unless @student.activated?
  end

  def new
    @student = Student.new
  end
  
  def create
    @student = Student.new(student_params)
    @student.activated = true
    if @student.save
      StudentMailer.account_activation(@student).deliver_now
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
private
  def student_params
   params.require(:student).permit(:studenttype, :name, :email, :password, :password_confirmation)
  end
    
  def logged_in_student
    unless logged_in?
        redirect_to root_url
    end
  end
  
  def current_logged_in_student
      @student = Student.find(params[:id])
      redirect_to error_path unless @student == current_student
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/error.html.erb
<%# 
This is a security feature. If I have student.id=3, then my profile is at ".../students/3", 
 when I am logged on, I cannot view another user's profiles i.e. I cannot access ".../students/1"
%>

<h1>You cannot view another user's profile</h1>

app/views/students/new.html.erb
<div class="text-center" style="padding:50px 0">
  <div class="logo">REGISTER</div>
  <!-- Main Form -->
  <div class="login-form-1">
    <%= form_for(@student) do |f| %>
    <form id="register-form" class="text-left">
      <div class="login-form-main-message"></div>
      <div class="main-login-form">
        <div class="login-group">
          
          
          <div class="form-group">
            <label for="reg_fullname" class="sr-only">Full Name</label>
            <%= f.text_field :name, placeholder: "Name" , class: "form-control"%>
           </div>

          <div class="form-group">
            <label for="reg_email" class="sr-only">Email</label>

            <%= f.email_field :email, placeholder: "Email Address", class: "form-control"%>
          </div>
             <div class="form-group">
            <label for="reg_password" class="sr-only">Password</label>
            <%= f.password_field :password, placeholder: "Password",class: "form-control" %>

          </div>
          <div class="form-group">
            <label for="reg_password_confirm" class="sr-only">Password Confirm</label>
                <%= f.password_field :password_confirmation, placeholder: "Password Confirmation" , class:"form-control" %>
          </div>
          
          <div class="form-group login-group-checkbox">
             <%= f.select :studenttype, [['Student','Student'],['Club Admin','Club Admin']] %>

          </div>
          
        </div>
        <%= f.submit "GO", class: "login-button" %>
        <button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
      </div>
      <div class="etc-login-form">
        <p>already have an account? <a href="/login">login here</a></p>
      </div>
    <%end%>
  </div>
  <!-- end:Main Form -->
</div>













       <!-- Error display -->
      <% if @student.errors.any? %>
        <div id="error_explanation">
          <h4><%= pluralize(@student.errors.count, "error") %> prohibited this article from being saved:</h2>
       
          <ul>
          <% @student.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      
    </div>
  </div>
  </div>

app/views/students/show.html.erb
<% require 'twitter_api' %>
<% provide(:title, @student.name) %>

<p>
  <h2>Welcome to SFUnite <%= @student.name %>!</h2>
</p>

<% if is_student? %>
  <p>You are logged in as a Student</p>
  <br>
<% else %> 
  <p>You are logged in as a Club Admin</p>
<% end %>

<% if !access_granted? %>
  <div>
    <strong>To show your personal calendar click <%= link_to "here",'/auth/google_oauth2' ,target: '_blank'%></strong>
  </div>
  <br>
<% end %>



  <%= button_to "My Clubs", myClubs_path, :method => :get %> 
  <%= button_to "Search or Browse All Clubs", allClubs_path, :method => :get %> 
  <%= button_to "Browse Clubs by Category", browseByCategory_path, :method => :get %>
  <% if !current_student.events.empty? %>
    <br>
    <%= button_to 'My Events', student_events_path, :method => :get %>
  <% end %>
  
  <br>
  
  

  
  <hr>
  <h2>Latest news from your Simon Fraser Student Society:</h2>
<ul>
  <% cache('sfss_tweets', expires_in: 2.hours)  do %>
  <% TwitterApi.sfss_tweets.each do |tweet| %>
  <li><%=parsed_tweet tweet %></li>  <%#= tweet.text %>
  <% end %>
  <% end %>
</ul>

<% if is_student? %>
<%#students cannot create clubs %>
<% else %> 
  <hr>
  <h2>Start a new club?</h2>
  <button id="displayclubform" onclick="displayclubform()">I want to start a new club!</button> 
<div id="DISPclubform" style="display:none;">
  <%= render 'clubs/clubForm' %>
  <button id="hideclubform" onclick="hideclubform()">Cancel</button> 
</div>

<% end %>

<% if access_granted? %>
  <hr>
<h2>My Calendar:</h2>
	<p><%= link_to('Plan your trip with translink', 'http://tripplanning.translink.ca/', target: '_blank') %>
    <br>
    </p>
  <div>
    <iframe src="<%= embed_link(current_student) %>" 
    style="border: 0" width="800" height="600" frameborder="0" scrolling="no">
    </iframe>
  </div>
<% end %>



<script>
      function displayclubform() {
    if (document.getElementById("DISPclubform").style.display == "block" ) {
       document.getElementById("DISPclubform").style.display="none";
    }
    else {
      document.getElementById("DISPclubform").style.display="block";
      }
    }  
    
    function hideclubform() {
       document.getElementById("DISPclubform").style.display="none";
    }  
</script>