config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  

  resources :clubs
  resources :students
  resources :sessions
  resources :events

#  root			        	'students#new'
 # get    'home'   =>  'static_pages#home'
#  get    'login'   => 'sessions#new'
#  post   'login'   => 'sessions#create'
#  delete 'logout'  => 'sessions#destroy'
  
#  get     'error' => 'students#error'



#resources :students
#resources :sessions
  resources :account_activations, only: [:edit]
  root 'static_pages#home'
  #root  'students#new'
  get   'contact' => 'static_pages#contact'
  get   'signup'  => 'students#new'
  get    'login'	=> 'sessions#new'
  post   'login'	=> 'sessions#create'
  delete 'logout'	=> 'sessions#destroy'
  get    'error'	=> 'students#error'
  get	 'myClubs'	=> 'clubs#list'
  get	 'allClubs'	=> 'clubs#index'
  get 'browseByCategory' => 'clubs#categories'
  post 'join'     => 'clubs#join'
  delete  'event' =>  'events#destroy'
  get    'signUp' => 'events#sign_up'
  get    'drop' => 'events#drop'
  get   'student_events' => 'events#student_events'
  
  
  # call back route from Google
  get "/auth/:provider/callback" => "sessions#access"

end


# comments are from the merge

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :club
	belongs_to :student
	
	validates	:name, presence: true
	validate :start_and_end_times
	
	def start_and_end_times
	  if self.start_time && (self.start_time > self.end_time)
	    self.errors.add(:start_time, "End time must be greater than start time.")
	  end
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	include ClubsHelper
	include EventsHelper
	include SessionsHelper

	def new
		@event = Event.new
		@club = Club.find_by(:name => params[:name])
	end

	def show
		@event = Event.find_by(:id => params[:id])
		@club = @event.club
	end
	
	def student_events
		@student = current_student
		@events = @student.events
	end

	def index
		@club = Club.find_by(:name => params[:name])
		@events = @club.events
	end

	def create
		club = Club.find_by(:name => params[:name])
		@event = Event.new(event_params)
		if !@event.save
			flash[:error] = 'Could not save event.'
			render 'new'
		else
			club.events << @event
			if access_granted_for_club?(club)
				calendar = Googlecalendarwrapper.new(club)
				@output = calendar.insert_event(hash_event(@event))
				@event.update_attribute(:google_id, @output["id"])
				flash[:message] = "Saved Event to Calendar"
			end
			redirect_to club
		end
	end
	
	def sign_up
		@event = Event.find_by(:id => params[:id])
		@student = Student.find_by(:name => params[:student])
		@student.events << @event
		if @student.google_account != nil
			calendar = Googlecalendarwrapper.new(@student)
			@output = calendar.insert_event(hash_event(@event))
			@student.update_attribute(:google_event_id, @output["id"])
			flash[:message] = "Saved Event to Calendar"
		end
		redirect_to current_student
	end
	
	def drop
		@event = Event.find_by(:id => params[:id])
		@student = Student.find_by(:name => params[:student])
		if @student[:google_event_id] != nil
			calendar = Googlecalendarwrapper.new(@student)
			calendar.delete_event(@student[:google_event_id])
			flash[:message] = "Deleted event from calendar."
		end
		@student.events.delete(@event)
		redirect_to current_student
	end

	def destroy
		@event = Event.find_by(:id => params[:id])
		club = @event.club
		
		if @event[:google_id] != nil
			calendar = Googlecalendarwrapper.new(club)
			calendar.delete_event(@event[:google_id])
			flash[:message] = "Deleted event from calendar."
		end
		@event.destroy
		redirect_to club
	end
	
	private
		def event_params
			params.require(:event).permit(:name, :description, :start_time, :end_time, :place)
		end
end

app/helpers/events_helper.rb
module EventsHelper
	
	def convert_time(time)
		# Format to YYYY-MM-DDTHH:MM:SS-07:00
		# e.g. 2016-08-01T12:00:00-07:00
		formatted_time = "#{time.year}-#{time.month}-#{time.day}T#{time.hour}:#{time.min}:#{time.sec}-07:00"
	end
	
	def hash_event(event)
		start_time = event[:start_time]
		end_time = event[:end_time]
		event_hash = {summary: event[:name],
			location: event[:place],
			start: {dateTime: convert_time(start_time)},
			end: {dateTime: convert_time(end_time)},
			description: event[:description]
		}
	end
end

app/views/events/create.html.erb
<%= @event[:name] %>
<br>
<%= @output["id"] %>

app/views/events/index.html.erb
<!DOCTYPE html>
<html>
<center>
	<h1> Club Events </h1>
	<p><%= link_to('Plan your trip with translink', 'http://tripplanning.translink.ca/', target: '_blank') %>
    <br>
    </p>
	<table class="table table-hover table-responsive table-responsive">
			<tr>
				<td></td>
				<td><strong>Name</strong></td>
				<td><strong>Description</strong></td>
				<td><strong>Starts at</strong></td>
				<td><strong>Ends at</strong></td>
			</tr>
			<% @events.each do |event| %>
			<tr>
				<td><%= button_to "View Event", event_path(event), { method: :get } %></td>
				<td><strong><%= event.name %></strong></td>
				<td><%= event.description %></td>
				<td><%= format_date(event.start_time) %></td>
				<td><%= format_date(event.end_time) %></td>
			</tr>
		<% end %>
	</table>
</center>


<style>
table {
    border-collapse: collapse;
    width: 100%;
    table-layout: fixed;
    overflow-x: auto;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
    word-wrap:break-word
}
tr:hover{background-color:#cce6ff}
</style>



</html>

app/views/events/new.html.erb
<h1><center>Create Event For</center></h1>
<h2><center><%= params[:name] %></center></h2>
<center>
  
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(@event.errors.count, "error") %>
        </div>
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for(:event, url: events_path) do |f| %>

      <table border ="0" style="border:none" height="300px">
      <tr>
      <td><%= f.label :name %></td>
      <td> <%= f.text_field :name, placeholder: "Event 1" %></td>
      </tr>
      <tr>
      <td><%= f.label :description %></td>
      <td><%= f.text_field :description %></td>
      </tr>
      <tr>
      <td> <%= f.label :start_time %></td>
      <td><%= f.datetime_select :start_time %></td>
      </tr>
      <tr>
      <td><%= f.label :end_time %></td>
      <td><%= f.datetime_select :end_time %></td>
      </tr>
      <tr>
      <tr>
      <td><%= f.label :place %></td>
      <td> <%= f.text_field :place %></td>
      </tr>
      <%# <tr><td>Click the button below to create your event:</td></tr>  %>
      <tr>
      <td>
        <%= hidden_field_tag(:name, params[:name]) %>
        <%= f.submit "Create Event" %></td>
      </tr>
      </table>
    <% end %>

<%#= image_tag("logo.jpg", :alt => "SFUnite logo") %>


</center>

app/views/events/show.html.erb
<% provide(:title, @club.name) %>
<div>
	<h1><%= @club.name %></h1>
	<h2><%= @event.name %></h2>
	<p><%= @event.description %></p>
	<p><%= @event.place %></p>
</div>
<hr>
<% if @club.admin_id == current_student.id %>
	<p>Club Admin: Click to delete this event</p>
	<%= button_to 'Delete', event_path, method: :delete, data: { confirm: "Are you sure you want to delete this event?" } %>
<% end %>
<hr>
<% if !current_student.events.exists?(name: @event.name) %>
	<p>Would you like to sign up for this event?</p>
	<%= button_to 'Sign Up Now', signUp_path, {:method => :get, :params => {:id => "#{@event.id}", :student => "#{current_student.name}"}} %>
<% else %>
	<p>You are currently signed up for this event. To drop this event from your calendar, click below.</p>
	<%= button_to 'Drop Event', drop_path, {:method => :get, :params => {:id => "#{@event.id}", :student => "#{current_student.name}"}} %>
<% end %>

app/views/events/student_events.html.erb
<center>
	<h1> Your Events </h1>
	<p><%= link_to('Plan your trip with translink', 'http://tripplanning.translink.ca/', target: '_blank') %>
    <br>
    </p>
    
	<table class="table table-hover table-responsive table-responsive">
			<tr>
				<td></td>
				<td><strong>Name</strong></td>
				<td><strong>Description</strong></td>
				<td><strong>Starts at</strong></td>
				<td><strong>Ends at</strong></td>
			</tr>
			<% @events.each do |event| %>
			<tr>
				<td><%= button_to "View Event", event_path(event), { method: :get } %></td>
				<td><strong><%= event.name %></strong></td>
				<td><%= event.description %></td>
				<td><%= format_date(event.start_time) %></td>
				<td><%= format_date(event.end_time) %></td>
			</tr>
		<% end %>
	</table>
</center>