config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  

  resources :clubs
  resources :students
  resources :sessions
  resources :events

#  root			        	'students#new'
 # get    'home'   =>  'static_pages#home'
#  get    'login'   => 'sessions#new'
#  post   'login'   => 'sessions#create'
#  delete 'logout'  => 'sessions#destroy'
  
#  get     'error' => 'students#error'



#resources :students
#resources :sessions
  resources :account_activations, only: [:edit]
  root 'static_pages#home'
  #root  'students#new'
  get   'contact' => 'static_pages#contact'
  get   'signup'  => 'students#new'
  get    'login'	=> 'sessions#new'
  post   'login'	=> 'sessions#create'
  delete 'logout'	=> 'sessions#destroy'
  get    'error'	=> 'students#error'
  get	 'myClubs'	=> 'clubs#list'
  get	 'allClubs'	=> 'clubs#index'
  get 'browseByCategory' => 'clubs#categories'
  post 'join'     => 'clubs#join'
  delete  'event' =>  'events#destroy'
  get    'signUp' => 'events#sign_up'
  get    'drop' => 'events#drop'
  get   'student_events' => 'events#student_events'
  
  
  # call back route from Google
  get "/auth/:provider/callback" => "sessions#access"

end


# comments are from the merge

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/static_pages/home.html">SFUnite</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if ((params[:controller] == 'static_pages') && (params[:action] == "contact")) %>"><a href="/contact">Contact</a></li>
        <% if logged_in? %> <%# only display this in drop down if student is logged in %>
        <li class="dropdown <%= 'active' if params[:controller] == 'clubs' %>">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Clubs<span class="caret"></span></a>
          <ul class="dropdown-menu">
            
            <li class="<%= 'active' if ((params[:controller] == 'clubs') && (params[:action] == "list")) %>"><a href="/myClubs">My Clubs</a></li>
            
            <li class="<%= 'active' if ((params[:controller] == 'clubs') && (params[:action] == "index")) %>"><a href="/allClubs">All Clubs List</a></li>
            <li class="<%= 'active' if ((params[:controller] == 'clubs') && (params[:action] == "categories")) %>"><a href="/browseByCategory">Clubs By Categories</a></li>
          </ul>
        </li>
        <%end%> <%# only display ^ this in drop down if student is logged in %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
       
        <% if !logged_in? %>

        <li class="<%= 'active' if params[:controller] == 'students' %>"><a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li class="<%= 'active' if params[:controller] == 'sessions' %>"><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>

        <%end%>

        <% if logged_in? %>
        

        <li><%= link_to "<span class='glyphicon glyphicon-dashboard'>My Dashboard</span>".html_safe, current_student, id: "mydashboardbutton" %></li>


        <li><%= link_to "<span class='glyphicon glyphicon-log-out'>Log out</span>".html_safe, logout_path, method: "delete", id: "logoutbutton"  %></li>
        <%end%>

      

      </ul>
    </div>
  </div>
</nav>


<div>
        <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>

<%= yield%>

</body>
  </html>